[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Handle PDF.js worker file as a static asset
[[headers]]
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*pdfjs-worker*"
  [headers.values]
    "Content-Type" = "application/javascript"
    "Cache-Control" = "public, max-age=31536000, immutable"

# Always redirect to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200